name: test-on-push 
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
            
      - name: Confirm Go
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.4.5
        
      - name: Confirm Terraform
        run: terraform --version

      - name: Get dependencies
        run: |
          go get -v -t -d ./... 

      - name: All Tests
        env:
          GOPROXY: "https://proxy.golang.org"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: go test -count=1 -v -timeout 5m ./...
