name: test-on-push 
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.15
          cache: false
            
      - name: Confirm Go
        run: go version

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.4.5
        
      - name: Confirm Terraform
        run: terraform --version

      - name: Setup Dependencies
        working-directory: tests/
        run:  go get -v -t -d && go mod tidy

      - name: All Tests
        working-directory: tests/
        run: go test -count=1 -v -timeout 5m
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
